### ISSUE TITLE
CMEK Permission errors when ingesting data

### ISSUE THREAD

**Issue by marktomlinson1** [GoogleCloudPlatform/cdmc#19]
Seeing the following errors from load_data.sh:

Access Denied: BigQuery BigQuery: Cloud KMS Error: Permission 'cloudkms.cryptoKeyVersions.useToEncrypt' denied on resource '<path>/cmek-bigquery-key' (or it may not exist). Please grant Cloud KMS CryptoKey Encrypter/Decrypter role to BigQuery service account: bq-projectnum@bigquery-encryption.iam.gserviceaccount.com

**Comment by swainjo** [comment]
@marktomlinson1 this runs successfully on a clean project, please test & close the issue.
