### ISSUE TITLE
Data scanning README updates needed

### ISSUE THREAD

**Issue by marktomlinson1** [GoogleCloudPlatform/cdmc#24]
Changes needed to the data scanning README

Step 1 - was already enabled via setup scripts
Step 2 - Variable replacements no longer needed
Step 3 - Scan period is now on line 121

**Comment by mtronci** [comment]
Fixed by https://github.com/GoogleCloudPlatform/cdmc/pull/33

**Comment by mtronci** [comment]
Fixed by https://github.com/GoogleCloudPlatform/cdmc/pull/33
