### ISSUE TITLE
Data Scanning script creates duplicate job triggers each time it is executed

### ISSUE THREAD

**Issue by marktomlinson1** [GoogleCloudPlatform/cdmc#25]
scan-data.sh / inspect_datasets.py script creates new DLP job triggers each time it is run. Multiple executions results in duplicate entries which soon hits the 1,000 job quota and there is no simple mechanism to delete. 

Previously running the script would immediately run the DLP jobs against the specified assets. Appears to have moved to a one-time setup activity. Would benefit from easy way to trigger on-demand for testing.

**Comment by swainjo** [comment]
rename the script to something like dlp-setup.sh and change scan-data.sh
