### ISSUE TITLE
More detail needed on permissions for initial SA defined in environment-variables.example

### ISSUE THREAD

**Issue by marktomlinson1** [GoogleCloudPlatform/cdmc#42]
Initial readme.md prompts user to update variables in environment-variables.sh copied from environment-variables.example with their own values. This includes:
 
export SERVICE_ACCOUNT_EMAIL="REPLACE WITH YOUR VALUE"

However details of how to create the service account and which permissions it needs is not included.

**Comment by mtronci** [comment]
@swainjo - is this required, or shall the AUTHORISED_USER be used instead?

**Comment by marktomlinson1** [comment]
The only place I can see it used is setup.sh and it's now commented out

**Comment by swainjo** [comment]
Fixed in https://github.com/GoogleCloudPlatform/cdmc/pull/48
